name: SuperTux
markdown: kramdown
highlighter: rouge
# baseurl: https://supertuxproject.org
exclude:
  - README.md
output: true

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

permalink: /news/:year/:month/:day/:title
timezone: UTC

paginate: 3
paginate_path: /news/:num
